#!/usr/bin/env bash

set -eu

www_dir="$(cd "$(dirname $0)"; pwd)"
fsl_dir="$www_dir/fsl.cs.illinois.edu"
repo_root="$www_dir/.."

cd "$fsl_dir"
mkdir -p _papers

# Install Jekyll and friends from Gemfile
bundle install

# Generate markdown files from bibtex
./bibtex2wiki/bibtex2wiki

# Generate Jekyll site
bundle exec jekyll "$@"
