#!/usr/bin/env bash

cd $(dirname $0)

# Reset gh-pages branch
git checkout -B gh-pages origin/gh-pages

# Commit to gh-pages branch
./git-commit-filetree gh-pages "fsl.cs.illinois.edu/_site"

# NOTE: you should manually git checkout gh-pages and push the commit. 

