#!/usr/bin/env bash

cd $(dirname $0)

# Build the website locally
# ./build build

# Commit to gh-pages branch
./git-commit-filetree gh-pages "fsl.cs.illinois.edu/_site"

# NOTE: you should manually git checkout gh-pages and push the commit. 

