#!/usr/bin/env bash

# Build the website locally
./build build

# Commit to gh-pages branch
cd "$www_dir"
./git-commit-filetree gh-pages "$fsl_dir/_site"

# NOTE: you should manually git checkout gh-pages and push the commit. 
